"""PII pattern data for Dutch B2B sales context.

Separated from pii_filter because the voornamen set is large.
"Mei" is intentionally excluded — month name creates too many false positives.
"""
from __future__ import annotations

import re

NL_VOORNAMEN: frozenset[str] = frozenset(
    {
        # Mannennamen
        "Ad",
        "Adriaan",
        "Anton",
        "Arjan",
        "Arno",
        "Bas",
        "Bert",
        "Bo",
        "Bram",
        "Cees",
        "Cor",
        "Daan",
        "Dennis",
        "Derk",
        "Dirk",
        "Erik",
        "Erwin",
        "Ferry",
        "Finn",
        "Floris",
        "Frans",
        "Frits",
        "Ger",
        "Geert",
        "Gijs",
        "Harm",
        "Hans",
        "Henk",
        "Hidde",
        "Hugo",
        "Jacco",
        "Jan",
        "Jasper",
        "Jayden",
        "Jelle",
        "Jens",
        "Jeroen",
        "Jesse",
        "Johan",
        "Joep",
        "Joost",
        "Jorn",
        "Julian",
        "Jurriaan",
        "Kevin",
        "Klaas",
        "Koen",
        "Lars",
        "Leon",
        "Liam",
        "Ludo",
        "Luuk",
        "Maarten",
        "Marcel",
        "Mark",
        "Martijn",
        "Max",
        "Michel",
        "Milan",
        "Niels",
        "Niek",
        "Noah",
        "Noa",
        "Oliver",
        "Patrick",
        "Paul",
        "Peter",
        "Pieter",
        "Piet",
        "Raymond",
        "Remco",
        "Remi",
        "Rene",
        "Richard",
        "Rick",
        "Rik",
        "Rob",
        "Robert",
        "Robbert",
        "Ronald",
        "Sam",
        "Sander",
        "Sem",
        "Simon",
        "Sjoerd",
        "Stef",
        "Stefan",
        "Theo",
        "Thijs",
        "Thomas",
        "Tijs",
        "Tim",
        "Timo",
        "Tobias",
        "Tom",
        "Wouter",
        "Willem",
        "Wim",
        # Vrouwennamen
        "Amber",
        "Amy",
        "Anke",
        "Anna",
        "Anouk",
        "Bente",
        "Bianca",
        "Carla",
        "Chantal",
        "Christel",
        "Claudia",
        "Daisy",
        "Demi",
        "Denise",
        "Dorien",
        "Elena",
        "Elise",
        "Elly",
        "Emma",
        "Esther",
        "Eva",
        "Femke",
        "Fenna",
        "Fien",
        "Fleur",
        "Floor",
        "Gabrielle",
        "Hanneke",
        "Hanna",
        "Ilse",
        "Ingrid",
        "Ines",
        "Iris",
        "Janna",
        "Janne",
        "Jolien",
        "Joke",
        "Julia",
        "Julie",
        "Karin",
        "Katja",
        "Kim",
        "Larissa",
        "Laura",
        "Lena",
        "Lies",
        "Liesbeth",
        "Lieke",
        "Linda",
        "Lisa",
        "Lisette",
        "Lotte",
        "Maaike",
        "Madelief",
        "Maike",
        "Manon",
        "Marianne",
        "Marieke",
        "Marjolein",
        "Marleen",
        "Mia",
        "Mila",
        "Mirjam",
        "Monique",
        "Naomi",
        "Natasja",
        "Nicky",
        "Nicole",
        "Nienke",
        "Noor",
        "Nora",
        "Olivia",
        "Patricia",
        "Petra",
        "Renate",
        "Rianne",
        "Romy",
        "Roos",
        "Sandra",
        "Sara",
        "Sascha",
        "Sien",
        "Silke",
        "Simone",
        "Sofie",
        "Sophie",
        "Tamara",
        "Tine",
        "Vera",
        "Vivian",
        "Wendy",
        "Yvonne",
    }
)

# Voornaam: case-sensitive word-boundary match — "jan" in email handles won't fire
PATTERN_VOORNAAM: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(n) for n in sorted(NL_VOORNAMEN)) + r")\b"
)

# Volledige naam met tussenvoegsel: "Jan van der Berg", "Piet de Vries"
PATTERN_ACHTERNAAM: re.Pattern[str] = re.compile(
    r"\b[A-Z][a-z]+\s+(?:van|de|der|den|ten|ter|te)\s+(?:[a-z]+\s+)?[A-Z][a-z]+\b"
)

# Datum in woorden: "5 mei 1985", "12 januari 2003"
PATTERN_DATUM_WOORD: re.Pattern[str] = re.compile(
    r"\b\d{1,2}\s+"
    r"(?:jan(?:uari)?|feb(?:ruari)?|mrt|maart|apr(?:il)?|mei"
    r"|jun(?:i)?|jul(?:i)?|aug(?:ustus)?|sep(?:tember)?"
    r"|okt(?:ober)?|nov(?:ember)?|dec(?:ember)?)"
    r"\s+\d{4}\b",
    re.IGNORECASE,
)

# Compact datum DDMMYYYY: "05051985" — validates day/month ranges to limit false positives
PATTERN_DATUM_COMPACT: re.Pattern[str] = re.compile(
    r"\b(?:0[1-9]|[12]\d|3[01])(?:0[1-9]|1[0-2])(?:19|20)\d{2}\b"
)
