#!/usr/bin/env python3
"""Build script that bakes the production Ed25519 public key into the package.

Usage (release build):
    SALES_COPILOT_PROD_PUBKEY_HEX=<hex> python scripts/embed_prod_pubkey.py

This writes ``src/sales_copilot/auth/_embedded_keys.py``. Development/test key
material lives in ``_dev_keys.py``, which is excluded from release artifacts.
There is no runtime environment variable that can alter the trusted keys after
the build.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_ED25519_PUBKEY_BYTES = 32


def _validate_hex(hex_value: str) -> str:
    hex_value = hex_value.strip().lower()
    if not re.fullmatch(r"[0-9a-f]{64}", hex_value):
        raise ValueError(
            f"public key must be {_ED25519_PUBKEY_BYTES * 2} hex chars, got {len(hex_value)}"
        )
    return hex_value


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Embed the production SCP public key at build time"
    )
    parser.add_argument(
        "--prod-hex",
        default=os.environ.get("SALES_COPILOT_PROD_PUBKEY_HEX", ""),
        help="Production Ed25519 public key as 64-char hex (default: SALES_COPILOT_PROD_PUBKEY_HEX env var)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("src/sales_copilot/auth/_embedded_keys.py"),
        help="Output path for the generated module",
    )
    args = parser.parse_args(argv)

    prod_hex = args.prod_hex.strip() or None
    if prod_hex is None:
        print(
            "error: no production public key to embed. Provide --prod-hex or "
            "SALES_COPILOT_PROD_PUBKEY_HEX.",
            file=sys.stderr,
        )
        return 1

    try:
        prod_hex = _validate_hex(prod_hex)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    content = f'''\"\"\"Build-time embedded public keys for SCP license verification.

This file is generated by ``scripts/embed_prod_pubkey.py``. Do not edit manually.
It contains ONLY production public key(s). Development/test key material lives in
``_dev_keys.py``, which is excluded from release artifacts.

Legal notice: this key material is part of the code that enforces the OnCue
commercial license. Removing or circumventing it to obtain Pro features
without a valid, paid license violates the OnCue commercial license and
applicable copyright law. See LICENSE-COMMERCIAL.md.
\"\"\"

from __future__ import annotations

# fmt: off
_PROD_PUBKEY_HEX: str | None = "{prod_hex}"
# fmt: on
'''

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")

    print(f"Wrote {args.out}")
    print("  production key embedded: True")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
