"""Build-time embedded public keys for SCP license verification.

This file is generated by ``scripts/embed_prod_pubkey.py``. Do not edit manually.
It contains ONLY production public key(s). Development/test key material lives in
``_dev_keys.py``, which is excluded from release artifacts.

Legal notice: this key material is part of the code that enforces the OnCue
commercial license. Removing or circumventing it to obtain Pro features
without a valid, paid license violates the OnCue commercial license and
applicable copyright law. See LICENSE-COMMERCIAL.md.
"""

from __future__ import annotations

# fmt: off
_PROD_PUBKEY_HEX: str | None = "91f67cba8811dd6b9ae68e940f440660b0e8ed73f74640ba57da5b54c806c2f0"
# fmt: on
