"""Build-time embedded public keys for SCP license verification.

This file is generated by ``scripts/embed_prod_pubkey.py``. Do not edit manually.
It contains ONLY production public key(s). Development/test key material lives in
``_dev_keys.py``, which is excluded from release artifacts.

Legal notice: this key material is part of the code that enforces the OnCue
commercial license. Removing or circumventing it to obtain Pro features
without a valid, paid license violates the OnCue commercial license and
applicable copyright law. See LICENSE-COMMERCIAL.md.
"""

from __future__ import annotations

# fmt: off
_PROD_PUBKEY_HEX: str | None = None
# fmt: on
